### ISSUE TITLE
Responsive Navbr

### ISSUE THREAD

**Issue by TanzimHossain2** [Codevware/formbuilder-cw#2]
![Screenshot 2023-06-24 065831](https://github.com/Codevware/formbuilder-cw/assets/60542516/83fdd2d3-d28c-4188-867c-55ceda4c1fed)
 
The login button shown in the middle, I can't left alignment.

**Comment by nadim-chowdhury** [comment]
Issue resolved

**Comment by TanzimHossain2** [comment]
🖤🖤
